### ISSUE TITLE
Code correction needed

### ISSUE THREAD

**Issue by agibsonIL** [rickert-lab/Italo#1]
https://github.com/rickert-lab/Italo/blob/3405fec75080f6709945b88a5abf698c3b10ead7/Italo.pyw#L201

This line is incorrectly using double quotes. Because of the nested quotes, this line of code needs to be refactored to the following.

```python
+ (f" at [{' | '.join(studies)}]." if studies else "."),
```

This changes `f" at [{" | ".join(studies)}]."` to `f" at [{' | '.join(studies)}]."`. The inner quotes are now single quotes.

**Comment by agibsonIL** [comment]
@christianrickert let me know if you receive this.

**Comment by christianrickert** [comment]
Hi @agibsonIL,

Which Python version are you using? - The `python` version specified for this project is v3.12+, see [requirements.txt](https://github.com/rickert-lab/Italo/blob/main/requirements.txt), and `ruff` v0.7.3 does not autocorrect the double quotation marks because it's not required anymore to mix quotation marks inside f-strings:

>Reusing the outer f-string quoting type inside a replacement field is permitted:
>```Python
>a = dict(x=2)
>f"abc {a["x"]} def"
>```
>Changed in version 3.12: Prior to Python 3.12, reuse of the same quoting type of the outer f-string inside a replacement field was not possible.

[Source](https://docs.python.org/3/reference/lexical_analysis.html#formatted-string-literals)

**Comment by agibsonIL** [comment]
I am using an older version of Python 3.7.9. I'm taking a look at the issue for the HALO 4.0 update and will let you know what I find.

**Comment by christianrickert** [comment]
That's great! - Thank you for looking into this issue.

If you need more input (logs), please let me know.
